target 'SwiftObserver' do

  use_frameworks!

  # Pods for SwiftObserver

  pod 'SwiftyToolz', '~> 1.4'

  target 'SwiftObserverTests' do
    inherit! :search_paths

    pod 'SwiftyToolz', '~> 1.4'

  end

end
