target 'SwiftObserver' do

  use_frameworks!

  # Pods for SwiftObserver

  pod 'SwiftyToolz', '~> 1.5'

  target 'SwiftObserverTests' do
    inherit! :search_paths

    pod 'SwiftyToolz', '~> 1.5'

  end

end
